---
configuration_directory: "%{cwd}/spec/unit/infra/root"
state_file: "%{cwd}/state/root.tfstate"
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"

  repository_name: "%{hiera('repository_name')}"
